CUDA_VISIBLE_DEVICES=2 python run_triviaqa.py \
  --model_type longformer \
  --model_name_or_path allenai/longformer-base-4096 \
  --output_dir outputs/triviaqa \
  --data_dir /home/mxdong/Data/triviaqa/squad_format \
  --train_file wikipedia-train-10.json \
  --predict_file wikipedia-dev-10.json \
  --max_seq_length 1024 \
  --doc_stride 256 \
  --max_query_length 32 \
  --do_train \
  --do_eval \
  --evaluate_during_training \
  --per_gpu_train_batch_size 1 \
  --per_gpu_eval_batch_size 16 \
  --learning_rate 2e-5 \
  --num_train_epochs 2.0 \
  --max_answer_length 30 \
  --fp16 \
  --fp16_opt_level O2 \
  --overwrite_output_dir \
#   --overwrite_cache \
